VILLAGERS = "villageois"
WOLVES = "loups-garous"
LOVERS = "amoureux"

GAME_START = "🎮 La partie vient de commencer !"
NIGHT_START = "🌙 La nuit tombe sur le village de Thiercelieux..."
THIEF_TURN = "🦹 Le voleur va pouvoir échanger, ou non, sa carte."
CUPID_TURN = "💘 Cupidon va pouvoir rendre deux personnes amoureuses."
SEER_TURN = "🔮 La voyante va pouvoir espionner un joueur."
WOLVES_TURN = "🐺 Les loups-garous vont décider d'une victime à dévorer."
WITCH_TURN = "🧪 La sorcière va pouvoir utiliser ses potions."
DAY_DEATHS = "☀️ Le village se réveille sans... {dead_players}."
DEAD_PLAYER = "le joueur {player_id} ({role_name})"
DEAD_PLAYERS_JOIN = "{players} et {last_player}"
LOVER_GRIEF = "🪦 Dans un élan de chagrin, le joueur {lover_id} ({role_name}), a décidé de rejoindre le joueur {dead_id} dans sa tombe."
DAY_NO_DEATH = "☀️ Le village se réveille et personne n'est mort pendant la nuit !"
# Le débat a influencé les suspicions des joueurs de x % + actions + égalité + supprimer les villageois vont pouvoir élire leur maire ? emoji tombe élimination par village
# bug d'affichage: 🪦 Dans un élan de chagrin, le joueur 8 (Villager), a décidé de rejoindre le joueur 6 dans sa tombe.
# ☀️ Le village se réveille sans... le joueur 6 (Villager) et le joueur 8 (Villager).
# 🗳️ Le village a décidé d'éliminer le joueur 12 (Hunter).
SHERIFF_TURN = "🗳️ Les villageois vont pouvoir élire leur maire."
SHERIFF_ELECTED = "🎖️ Le joueur {sheriff_id} a été élu maire du village."
SHERIFF_SUCCESSOR = "🎖️ Le joueur {player_id} a été désigné comme nouveau maire du village."
VOTE_ELIMINATION = "🗳️ Le village a décidé d'éliminer le joueur {target_id} ({role_name})."
HUNTER_SHOT = "🎯 PAN ! Le chasseur a décidé d'exécuter le joueur {target_id} ({role_name})."
HUNTER_NO_SHOT = "🎯 Par sa toute bonté, le chasseur n'a finalement exécuté personne."
GAME_OVER = "🏆 La partie est terminée ! Les {winner} ont gagné !"

SERVER_THIEF_SWAP = "ℹ️ Le voleur a échangé sa carte et devient {role_name}."
SERVER_THIEF_KEEP = "ℹ️ Le voleur a conservé sa carte et devient donc {role_name}."
SERVER_CUPID_LOVERS = "ℹ️ Cupidon a rendu amoureux les joueurs {lover1_id} et {lover2_id}."
SERVER_SEER_SPY = "ℹ️ La voyante a espionné le joueur {target_id} ({role_name})."
SERVER_WOLVES_TARGET = "ℹ️ Les loups-garous ont décidé de dévorer le joueur {target_id}."
SERVER_WITCH_POISON = "ℹ️ La sorcière a empoisonné le joueur {target_id} avec sa potion de mort."
SERVER_WITCH_SAVE = "ℹ️ La sorcière a sauvé le joueur {target_id} grâce à sa potion de vie."
SERVER_WITCH_NO_ACTION = "ℹ️ La sorcière n'a utilisé aucune potion."

STATS_TITLE = "📊 WEREWOLF SIMULATION RESULTS"
STATS_FACTION = "Faction"
STATS_WINS = "Wins"
STATS_WIN_RATE = "Win rate"
STATS_GAMES_RUN = "Games run: {n_games}"
